changelog:
  exclude:
    authors:
      - dependabot[bot]
      - github-actions[bot]
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Improvements
      labels:
        - improvement
        - refactor
    - title: Other Changes
      labels:
        - '*'
